### ISSUE TITLE
Test Seeding Report Defaults

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#152]
The tests created for this issue will test the default contents of the Seeding Report page in the BarnKit.

These tests must check that the:
- [x] - page contains the header "Seeding Report"
- [x] - page contains a section labeled "Set Dates"
- [x] - button has the label "Generate Report" and is enabled.
- [x] - default start date is the first day of the current year.
- [x] - default end date is the current date.
- [x] - the remainder of the report is not visible or does not exist.

Other information:
 - The source code and tests for the Seeding Report will be in the `farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport` directory.
 - The `seedingReport.html` file contains the source code for the page.
 - The tests for this issue should be created in a new file named `seedingReport.defaults.spec.js`
 - The above tests should be broken up into logically organized `it` blocks within the test file.

**Comment by braughtg** [comment]
Some additional notes:
  - It is not necessary to include a separate `it` for each of the things to be tested.
  - You should decide how to divide the things being tested into `it`s so that each `it` tests a cohesive set of things.
  - The message for each `it` should describe in a short phrase what the `it` is testing.
  - The `.spec.js` file should include a comment at the top that describes what the file as a whole is testing.
  - The message for the `describe` should describe in a short phrase what the file is testing.
  - **The `.spec.js` files in the `farmdata2/farmdata2_modules/fd2_example/` sub-tabs (e.g. `ui`, `api`) may provide some helpful examples.**

**Comment by saiatl2354** [comment]
I would like to work on this.

**Comment by Melantha-Chen** [comment]
I would like to work on this
