### ISSUE TITLE
Test Seeding Input Direct Seeding Defaults

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#159]
The tests created for this issue will test the default contents of the "Direct Seeding" section of the Seeding Input Form in the FieldKit.

These tests must check that the Direct Seeding section of the Seeding Input Form:
- [x] - appears when "Direct" is selected
- [x] - has a dropdown for the Area that is enabled
- [x] - that the dropdown contains the correct list of fields for the sample farm.
- [x] - that there is a field for "Row/Bed" that is empty and enabled. 
- [x] - that there is a field for "Bed Feed" that is empty and enabled.
- [x] - that there is a dropdown for units that is enabled.
- [x] - that the options for the dropdown are "Bed Feet" and "Row Feet"
- [x] - that "Bed Feet" is the default units

Other information:
 - The source code and tests for the Seeding Input Form will be in the `farmdata2/farmdata2_modules/fd2_field_kit/seedingInput` directory.
 - The `seedingInput.html` file contains the source code for the page.
 - The tests for this issue should be created in a new file named `seedingInput.direct.defaults.spec.js`
 - The above tests should be broken up into logically organized `it` blocks within the test file.

**Comment by JinLeeGG** [comment]
I would like to work on this!

**Comment by won369369** [comment]
I would like to work on this!

**Comment by braughtg** [comment]
Some additional notes:
  - It is not necessary to include a separate `it` for each of the things to be tested.
  - You should decide how to divide the things being tested into `it`s so that each `it` tests a cohesive set of things.
  - The message for each `it` should describe in a short phrase what the `it` is testing.
  - The `.spec.js` file should include a comment at the top that describes what the file as a whole is testing.
  - The message for the `describe` should describe in a short phrase what the file is testing.
  - **The `.spec.js` files in the `farmdata2/farmdata2_modules/fd2_example/` sub-tabs (e.g. `ui`, `api`) may provide some helpful examples.**

**Comment by Shahir-47** [comment]
I would like to work on this!

**Comment by johnmaccormick** [comment]
Hi, it looks like the filename for your tests is not correct.

**Comment by johnmaccormick** [comment]
You have used some advanced Cypress techniques for managing the browser's local storage, if I understand correctly. All tests are passing, so that's great. But I would like to seek the opinion of a farmdata2 maintainer about whether it is a good idea to use these advanced techniques. I'm referring to the use of

* `localStorage.removeItem()`
* `cy.restoreLocalStorage()`
* `cy.saveLocalStorage()`
* `cy.intercept()`
* `cy.wait()`

Perhaps Prof Braught @braughtg  can comment on this.

**Comment by johnmaccormick** [comment]
I have another question about your advanced techniques. When checking the size of the list of areas, you compare it to the content of `JSON.parse(localStorage.getItem('areas'))`  -- but this raises an interesting question about testing technique. How do we know that the correct list was fetched and stored into the local storage? If we test that the fetched list has the same length as the drop-down list, have we covered the most likely type of errors intended to be covered by this test? I'm not sure of the answer, but I'm wondering if a simpler approach with a hardcoded length would be more robust. Interesting question for discussion.

**Comment by johnmaccormick** [comment]
Overall, I think you've done good work on this issue and once the file name is correct there is a good chance it can be merged. Nice job!

**Comment by johnmaccormick** [comment]
oops ... my mistake ... I added a bunch of review comments above -- they should have been added to the PR, not here in the Issue.  I will delete the comments I added and move them into [PR 182](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/182). Sorry for the confusion.
