### ISSUE TITLE
Test Seeding Input Miscellaneous Defaults

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#160]
The tests created for this issue will test some miscellaneous default contents of the Seeding Input Form in the FieldKit that did not fit into other tests:

These tests must check that the Seeding Input Form:
- [x] - has a page header of "Seeding Input Log"
- [x] - has a section with the label "Comments"
- [x] - the comments section has a text area that is enabled and empty.
- [x] - the page contains a button labeled "Submit"
- [x] - the "Submit" button is disabled

Other information:
 - The source code and tests for the Seeding Input Form will be in the `farmdata2/farmdata2_modules/fd2_field_kit/seedingInput` directory.
 - The `seedingInput.html` file contains the source code for the page.
 - The tests for this issue should be created in a new file named `seedingInput.misc.defaults.spec.js`
 - The above tests should be broken up into logically organized `it` blocks within the test file.

**Comment by braughtg** [comment]
Some additional notes:
  - It is not necessary to include a separate `it` for each of the things to be tested.
  - You should decide how to divide the things being tested into `it`s so that each `it` tests a cohesive set of things.
  - The message for each `it` should describe in a short phrase what the `it` is testing.
  - The `.spec.js` file should include a comment at the top that describes what the file as a whole is testing.
  - The message for the `describe` should describe in a short phrase what the file is testing.
  - **The `.spec.js` files in the `farmdata2/farmdata2_modules/fd2_example/` sub-tabs (e.g. `ui`, `api`) may provide some helpful examples.**

**Comment by tainguyen103** [comment]
I will work on this issue

**Comment by vuphuongha** [comment]
I will be working on this issue.

**Comment by jamesng5** [comment]
I will be working on this issue

**Comment by jamesng5** [comment]
Our team are working on #211

**Comment by braughtg** [comment]
> I do not see the "Generate button"

Both the 4th and 5th tasks should say "Submit Button" rather than "Generate Report." 

Thanks for pointing it out. I will edit the original issue text to correct this.

**Comment by johnmaccormick** [comment]
4 of 5 tasks look good -- please take a look at the missing one

**Comment by vuphuongha** [comment]
<img width="1029" alt="Screenshot 2023-04-21 at 12 26 31 PM" src="https://user-images.githubusercontent.com/60118892/233687338-73d07d87-dd9f-43f9-9b07-623ead3d4b0a.png">

The E2E tests I ran using Cypress worked fine. Would you mind checking again? Thanks!

**Comment by johnmaccormick** [comment]
> 4 of 5 tasks look good -- please take a look at the missing one

Sorry for my previous comment, this was mistakenly entered in the Issue but I should have put it on the PR. As you can see, I am still learning about the review process and workflow. I will update the PR with relevant comments.

**Comment by johnmaccormick** [comment]
> The E2E tests I ran using Cypress worked fine. Would you mind checking again? Thanks!

Sure @vuphuongha, no problem, I will put my comments over in the PR this time.

**Comment by vuphuongha** [comment]
Sounds good professor @johnmaccormick. Please let me know if there's any issues we need to fix asap. Thanks!

**Comment by johnmaccormick** [comment]
@vuphuongha -- Thanks for your question. In truth, I did not really think about how the team 5-15 reports would affect the process of making pull requests on feature branches. Next year if I am teaching this course I will figure out a different way to approach this. I think the best solution for now is to move your 5-15 reports to a separate branch - call the branch "reports" and put both of your team reports there, in a folder that is also called "reports" at the root of your repository.
