### ISSUE TITLE
Seeding Report: Test Crop Filter

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#187]
The tests should generate seeding reports as appropriate to check that:
  - [x] - when “All” is selected in the Crop filter, the table will contain logs for seedings for multiple different crops.
  - [x] - when a specific crop is selected in the Crop filter, the table will contain only seeding logs for the selected type of crop.
  - [x] - the dropdown for the Crop filter contains only crops for which there are seeding logs in the date range used to generate the report.

**Comment by braughtg** [comment]
Some additional notes relevant to this issue:
  - In addition to logging in and visiting the desired page the `beforeEach` method should also call `cy.waitForPage()`.  This will ensure that the page is fully loaded (e.g. that all the `Maps` used by the page are loaded) before performing any tests.
  - It is not necessary to include a separate `it` for each of the things to be tested.
  - You should decide how to divide the things being tested into `it`s so that each `it` tests a cohesive set of things.
  - The message for each `it` should describe in a short phrase what the `it` is testing.
  - The `.spec.js` file should include a comment at the top that describes what the file as a whole is testing.
  - The message for the `describe` should describe in a short phrase what the file is testing.
  - **The `.spec.js` files in the `farmdata2/farmdata2_modules/fd2_example/` sub-tabs (e.g. `ui`, `api`) may provide some helpful examples.**

**Comment by pranavm2109** [comment]
I would like to work on this please!

**Comment by Alexandrialexie** [comment]
I would like to work on this one, please.

**Comment by andrewscheiner53** [comment]
I would like to work on this!
