### ISSUE TITLE
BarnKit Tab: Test for BarnKit Sub-Tabs

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#201]
FarmData2 adds the BarnKit tab to the farmOS user interface.  

This test must check that:
  - [ ] - The BarnKit tab contains sub-tabs for “Info”, “Seeding Report” and “Transplanting Report”
  - [ ] - The order of the tabs is “Info”, “Seeding Report” and then “Transplanting Report.”
  - [ ] - There are the correct number of sub-tabs (~~2~~ 3 at this time).

**Notes:**
  - The `spec.js` for this test should be created in the `cypress` directory in the `fd2_barn_kit` directory.

**Challenges:**
  - The HTML for these tabs is generated by farmOS and thus will not have `data-cy` attributes, and you will not be able to add them.  Thus, you will need to do some research to find an effective way to `cy.get` the HTML element for the tab.  The resources below may be helpful.
  - Because, over time the UI may evolve and change (e.g. new tabs may be added) your tests should not rely on the specific ordering of the tabs in the UI.  That is, you should be careful that your test would still pass if new tabs are added or the tabs are reordered.  E.g. you should not rely on the BarnKit tab being the 3rd child of some other element.

**Resources:**
  - Cypress Locators: The ways that `cy.get` finds elements in the page.  We have used `data-cy` attributes up to this point.  But there are other types of locators.
    - [Cypress Locators : How to find HTML elements](https://www.browserstack.com/guide/find-html-element-using-cypress-locators)
    - [Cypress Locators](https://www.toolsqa.com/cypress/cypress-locators/)
  - Cypress Selector Playground: The selector playground is part of the Cypress application that can help with finding and testing locators that can be used with `cy.get`.
    - [Cypress Selector Playground](https://www.youtube.com/watch?v=rNd047wXtwo)
  - Browser DevTools Element Inspector: A tool built into the browser’s DevTools that can help you find the source code for a specific element in the page. 
    - [Firefox Element Inspector](https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/open_the_inspector/index.html)

**Comment by udvale** [comment]
I would like to work on this!

**Comment by thorpIV** [comment]
I would like to work on this!
